First UI tests (fixes #289)
redhat-developer/vscode-tekton pull request #612
Opened 2021-08-03 14:02 UTC by jkopriva

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

2021-08-03 14:03 UTC, jkopriva commented
@jrichter1 please review and share your thoughts :)

2021-08-04 09:30 UTC, jrichter1 requested changes

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/common/conditions.ts
> +export async function notificationCenterIsOpened(): Promise<boolean | undefined> {
This looks like it only returns `boolean`

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/common/conditions.ts
> +    for (const title of titles) {
the `const title` is masking the method argument

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/common/utils.ts
> +  await terminalView.executeCommand('oc login --username=' + username + ' --password=' + password + ' --server=' + clusterUrl + ' --insecure-skip-tls-verify');
I'd recommend using template string for this.
```typescript
await terminalView.executeCommand(`oc login --username=${username} --password=${password} --server=${clusterUrl} --insecure-skip-tls-verify`);
```
Looks better I think

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/common/utils.ts
> +export async function clearNotifications(): Promise<undefined> {
This could be a `Promise<void>`, then it would work without the `return null` line.

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/task-test.ts
> +      loginToOpenShiftWithTerminal(clusterUrl, username, password);
missing await

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +      loginToOpenShiftWithTerminal(clusterUrl, username, password);
missing await

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +      driver.sleep(1000);
missing await

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +      driver.sleep(1000);
missing await

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +      await (await new ActivityBar().getViewControl(views.TEKTON_TITLE)).openView();
the same duplicate view opening as in the previous test file

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +      await (await new ActivityBar().getViewControl(views.TEKTON_TITLE)).openView();
same as above

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +      const tektonSection = await new SideBarView().getContent().getSection(views.TEKTON_TITLE) as CustomTreeSection;
the first line is a subset of the second, has no real value

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +      await (await new ActivityBar().getViewControl(views.TEKTON_TITLE)).openView();
again the duplicated control code

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +      await (await new ActivityBar().getViewControl(views.TEKTON_TITLE)).openView();
and again

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +      const tektonSection = await new SideBarView().getContent().getSection(views.TEKTON_TITLE) as CustomTreeSection;
duplicated section code

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/tekton-view-test.ts
> +        const itemPipelines = await tektonSection.findItem(item) as unknown as ExtensionsViewItem;
I don't think you will find `ExtensionsViewItem` in a `CustomTreeSection`. My bet would be on `CustomTreeItem`, that should let you cast without using `unknown`.

2021-08-04 09:30 UTC, jrichter1 commented on ui-test/suite/task-test.ts
> +      await (await new ActivityBar().getViewControl(views.TEKTON_TITLE)).openView();
The first two lines together make the third line. I think you only need to open the view once, so I'd keep the third line only.

2021-08-09 08:39 UTC, jrichter1 commented
LGTM

2021-08-09 08:52 UTC, evidolob approved these changes

2021-08-09 08:53 UTC, merged