Build for main branch
redhat-developer/vscode-tekton pull request #649
Opened 2021-11-22 13:26 UTC by sudhirverma

2021-11-22 15:02 UTC, mohitsuman requested changes

2021-11-22 15:02 UTC, mohitsuman commented on .github/workflows/codeql-analysis.yml
> +      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
@sudhirverma Same space fix here.

2021-11-22 15:02 UTC, mohitsuman commented on .github/workflows/codeql-analysis.yml
> +      - name: Perform CodeQL Analysis
@sudhirverma Same space fix here.

2021-11-22 15:02 UTC, mohitsuman commented on pipeline-examples/output-pipelinerun.yaml
> +    - name: revision
@sudhirverma Same space fix here.

2021-11-22 15:02 UTC, mohitsuman commented on pipeline-examples/output-pipelinerun.yaml
> +    - name: first-create-file # 1. create file
@sudhirverma It's mostly in the entire file. I don't think we need space fix here. Apart from extra spaces fix end of line. Please have a good look.

2021-11-22 21:24 UTC, mohitsuman commented
This PR will fix #648 . @sudhirverma once merged, please rename the master to main to complete the issue fix.

2021-11-22 21:24 UTC, mohitsuman approved these changes

2021-11-23 07:57 UTC, evidolob approved these changes

2021-11-23 08:26 UTC, merged