release 1.0.0
redhat-developer/vscode-tekton pull request #650
Opened 2021-11-23 09:02 UTC by sudhirverma

2021-11-23 12:47 UTC, evidolob approved these changes

2021-11-24 07:55 UTC, mohitsuman requested changes

2021-11-24 07:55 UTC, mohitsuman commented on CHANGELOG.md
> +## 1.0.0 (November 23, 2021)
```suggestion
## 1.0.0 (November 24, 2021)
```

2021-11-24 08:12 UTC, mohitsuman approved these changes

2021-11-24 08:30 UTC, merged